# Generated by Django 5.0.1 on 2024-01-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['-tipo'], 'verbose_name': 'Habitacion', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='persona',
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='imagen',
            field=models.ImageField(upload_to='habitaciones', verbose_name='Imagen'),
        ),
    ]
